### ISSUE TITLE
how to use cypress inside VNC server

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/dev-stock#139]
I'm seeing https://github.com/pondersource/dev-stock/blob/5e0bf8dfb8db2cdfc281d0fc40d0ce533c54ce00/dev/ocm-test-suite/login/nextcloud.sh#L194

I added the /vnc_auto.html at the end of the URL but I still can't see how to use it. Is there documentation about this?

**Comment by michielbdejong** [comment]
Hm, still seeing "What's new in Cypress" on a page that doesn't fit in the viewport

**Comment by MahdiBaghbani** [comment]
Indeed it need documentation, I'll do one with pictures

**Comment by michielbdejong** [comment]
Screensharing now.
```
./dev/ocm-test-suite.sh login nextcloud v27.1.10 dev electron
```

**Comment by michielbdejong** [comment]
In the controls on the left of the VNC screen, click 'scaling' -> 'local' and click 'continue'
