### ISSUE TITLE
Testing OCM suite on Mac

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/dev-stock#140]
I'm testing on my laptop:
```
./scripts/clean.sh
./init/ocm-test-suite.sh
./dev/ocm-test-suite/login/nextcloud.sh v28.0.7 dev
docker exec -it nextcloud1.docker cat config/config.php
docker exec -it nextcloud1.docker mysql -h marianextcloud1.docker -u oc_einstein -p\!4{B[v#]eWtZFOrsec4+%7qRi7Q\;ZD -e 'select * from oc_users;' efss
```
Logging in through embedded firefox works.
I can't see what to do on http://localhost:5700 -> #139
Otherwise this one works! Will test the other ones as well and log here any issues I encounter.

**Comment by michielbdejong** [comment]
```
./dev/ocm-test-suite/login/ocis.sh 5.0.6 dev
```
The cert isn't trusted by Firefox but that is not a big problem. Otherwise, it works!

**Comment by michielbdejong** [comment]
```
./dev/ocm-test-suite/login/owncloud.sh v10.14.0 dev
docker exec -it owncloud1.docker cat config/config.php
docker exec -it owncloud1.docker mysql -h mariaowncloud1.docker -u oc_marie -pVFI13Fxs5xUzmME4ipgCH8flRAl0RE -e 'select * from oc_users;' efss
```
password einstein / relativity is rejected.

**Comment by michielbdejong** [comment]
```
./dev/ocm-test-suite/login/seafile.sh 11.0.5 dev
```
FIXME: you will see Page unavailable on http://seafile1.docker/accounts/login/?next= -> #141

**Comment by MahdiBaghbani** [comment]
I really should start working on a Macbook (Air) sometime soon. I kinda like to use long flag format 😄

**Comment by michielbdejong** [comment]
I got this working now
