### ISSUE TITLE
unable to manually log in to seafile

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/dev-stock#141]

**Comment by michielbdejong** [comment]
maybe the user is not einstein?

**Comment by michielbdejong** [comment]
Maybe I should specify https://github.com/pondersource/dev-stock/blob/e4c041e45f715c01039647dffb12bb4527e5bc7a/dev/ocm-test-suite/login/seafile.sh#L59-L60

```
./dev/ocm-test-suite/login/seafile.sh 11.0.5 dev einstein relativity
```

Although I tried this and it didn't seem to help

**Comment by michielbdejong** [comment]
I'll try with:
```
./dev/ocm-test-suite.sh login seafile 11.0.5 dev electron
```

**Comment by michielbdejong** [comment]
Hm, same result still
<img width="790" alt="Screenshot 2024-08-28 at 14 34 16" src="https://github.com/user-attachments/assets/580766c8-7c54-4832-827e-f8dbfabe86b1">

**Comment by MahdiBaghbani** [comment]
> maybe the user is not einstein?

Yes, user name and password are defined here as `jonathan@seafile.com` and `xu`

https://github.com/pondersource/dev-stock/blob/e4c041e45f715c01039647dffb12bb4527e5bc7a/dev/ocm-test-suite/login/seafile.sh#L138
