### ISSUE TITLE
Add http.services.ocmprovider to revanc1.toml,revanc2.toml,revaoc1.toml,revaoc2.toml

### ISSUE THREAD

**Issue by parhamin2010** [pondersource/dev-stock#21]
nc1:
`[http.services.ocmprovider]
ocm_prefix = "ocm"
provider = "revanc1@cern"
endpoint = "http://localhost:19001"
enable_webapp = true
enable_datatx = true`

nc2:
`[http.services.ocmprovider]
ocm_prefix = "ocm"
provider = "revanc2@cern"
endpoint = "http://localhost:19001"
enable_webapp = true
enable_datatx = true`

oc1:
`[http.services.ocmprovider]
ocm_prefix = "ocm"
provider = "revaoc1@cern"
endpoint = "http://localhost:19001"
enable_webapp = true
enable_datatx = true`

oc2:
`[http.services.ocmprovider]
ocm_prefix = "ocm"
provider = "revaoc2@cern"
endpoint = "http://localhost:19001"
enable_webapp = true
enable_datatx = true`

**Comment by MahdiBaghbani** [comment]
added in fd5c3316bb05dcfb0e687ac7d165bec884e0168e.
