### ISSUE TITLE
show x-debug exceptions in nextcloud server source

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/dev-stock#4]
```
cd /workspace/dev-stock
git clone --depth=1 https://github.com/nextcloud/server
cd /var/www/html
sudo ln -s /workspace/dev-stock/server/lib
```

That way X-Debug has the server source code on the host in the place where it expects it, and it can display QueryNotFoundException errors instead of offering 'Create file'

**Comment by michielbdejong** [comment]
Not sure if this is the right approach or we can somehow tell X-Debug / VSCode that it should be looking for `/var/www/html` inside the container instead of on the host.

**Comment by MahdiBaghbani** [comment]
based on the documentation you can always map the xdebug from host to container, basically telling it that all the files and directories under `/a/b/c` path should be searched under `/aaa/bbb/ccc` on the host.

```
            "pathMappings": {
                "/var/www/html/apps/sciencemesh": "${workspaceFolder}/nc-sciencemesh"
            }
```

we can even configure multiple xdebug launch instructions based on our needs and do different path mappings.

examples:

for Sciencemesh
```
        {
            "name": "Listen for Xdebug Sciencemesh",
            "type": "php",
            "request": "launch",
            "port": 9003,
            "pathMappings": {
                "/var/www/html/apps/sciencemesh": "${workspaceFolder}/nc-sciencemesh"
            }
        }
```

for Nextcloud
```
        {
            "name": "Listen for Xdebug Nextcloud",
            "type": "php",
            "request": "launch",
            "port": 9003,
            "pathMappings": {
                "/var/www/html": "${workspaceFolder}/server/lib"
            }
        }
```

and even on the cases when we have no code available on the host (no git clone, etc) we can use docker to map the container's volume into host then do the path mapping in launch.json like the examples.
