### ISSUE TITLE
Why mount nextcloud/server and owncloud/core for ScienceMesh testing?

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/dev-stock#41]
For our ScienceMesh apps we don't have to do any changes or development in nextcloud/server and owncloud/core, so why are we mounting them?

https://github.com/pondersource/dev-stock/commit/89d8e3d07810c3dbdf4a903b9cef0ada0c3ebdd7#diff-941c6302f183b2b5b4552a6984ed273037783ace849355f6e3bf8c2858603d23R33

**Comment by MahdiBaghbani** [comment]
We need to search core and server while trying to debug/trace code, I found it is easier to do it on VSCode rather than opening GitHub on the browser.

**Comment by michielbdejong** [comment]
Good reason! :)
