### ISSUE TITLE
error on running ./scripts/oc-opencloudmesh-testing.sh

### ISSUE THREAD

**Issue by navid-shokri** [pondersource/dev-stock#7]
{"reqId":"bAC6TAp3ZQJtPTGi7TCG","level":3,"time":"2023-04-17T11:33:37+00:00","remoteAddr":"172.19.0.6","user":"--","app":"index","method":"GET","url":"\/index.php","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Class 'OCA\\\\OpenCloudMesh\\\\ShareProviderFactory' not found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(122): OC\\\\Server->OC\\\\{closure}(*** sensitive parameters replaced ***)\\n#1 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(107): Pimple\\\\Container->offsetGet()\\n#2 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/ServerContainer.php(86): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query()\\n#3 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Server.php(1678): OC\\\\ServerContainer->query()\\n#4 \\\/var\\\/www\\\/html\\\/apps\\\/files_sharing\\\/lib\\\/AppInfo\\\/Application.php(165): OC\\\\Server->getShareManager()\\n#5 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(122): OCA\\\\Files_Sharing\\\\AppInfo\\\\Application->OCA\\\\Files_Sharing\\\\AppInfo\\\\{closure}(*** sensitive parameters replaced ***)\\n#6 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(107): Pimple\\\\Container->offsetGet()\\n#7 \\\/var\\\/www\\\/html\\\/apps\\\/files_sharing\\\/lib\\\/AppInfo\\\/Application.php(207): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query()\\n#8 \\\/var\\\/www\\\/html\\\/apps\\\/files_sharing\\\/appinfo\\\/app.php(38): OCA\\\\Files_Sharing\\\\AppInfo\\\\Application->registerMountProviders()\\n#9 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/legacy\\\/app.php(253): require_once('\\\/var\\\/www\\\/html\\\/a...')\\n#10 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/legacy\\\/app.php(192): OC_App::requireAppFile()\\n#11 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/legacy\\\/app.php(125): OC_App::loadApp()\\n#12 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(901): OC_App::loadApps()\\n#13 \\\/var\\\/www\\\/html\\\/index.php(54): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Server.php\",\"Line\":903}"}

**Comment by navid-shokri** [comment]
I checked it and the file mounting is not accurate

**Comment by michielbdejong** [comment]
What is the file mounting, and in which way is it not accurate? Can you fix it? Should this issue be reopened?
