### ISSUE TITLE
[OCM] Add FOSS alternative or for CI pipelines in general.

### ISSUE THREAD

**Issue by MahdiBaghbani** [pondersource/dev-stock#72]
Could we ensure it works not only for GitHub Actions (as some people tend to do..), but also for some FOSS alternatives or CI pipelines in general?

Candidates:
1. Gitlab CI
2. Jenkins
3. CircleCI
4. Travis CI

**Comment by MahdiBaghbani** [comment]
I plan to implement CI for all 4 candidates, I need to read docs and play a little bit with them to understand what is needed to run the OCM test suite.

I've created some kind of gitlab-ci.yaml file for GitLab Runner needs tweaking and testing, haven't pushed it yet.

**Comment by michielbdejong** [comment]
@MahdiBaghbani I think just GitLab will be enough, then we can claim the milestone.
In the end it should hopefully be quite similar between CI platforms since it's all bash/docker based, right?

**Comment by MahdiBaghbani** [comment]
@michielbdejong It is same between GitHub and GitLab since everything is dockerized 👍🏼
