### ISSUE TITLE
`testnet` network not found error.

### ISSUE THREAD

**Issue by navid-shokri** [pondersource/dev-stock#9]
after calling `./scripts/init-rd-sram.sh` and `init-oc-opencloudmesh.sh`  I am facing with this error on calling `./scripts/oc-opencloudmesh-testing.sh` 

 > docker: Error response from daemon: network testnet not found.

it seems the `testnet` network is not created on previous commands.

**Comment by MahdiBaghbani** [comment]
Has been fixed for a while.
